### ISSUE TITLE
Conversion Error

### ISSUE THREAD

**Issue by M3ssman** [OCR-D/ocrd_segment#29]
When using the ocrd-segment-repair, I've encountered the following Error

```
10:30:48.758 INFO processor.RepairSegmentation - Sanitizing region "region0071"
/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/bin/ocrd-segment-repair", line 8, in <module>
    sys.exit(ocrd_segment_repair())
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/ocrd_segment/cli.py", line 13, in ocrd_segment_repair
    return ocrd_cli_wrap_processor(RepairSegmentation, *args, **kwargs)
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/ocrd/decorators.py", line 60, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/ocrd/processor/base.py", line 57, in run_processor
    processor.process()
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/ocrd_segment/repair.py", line 88, in process
    self.sanitize_page(page, page_id)
  File "/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/ocrd_segment/repair.py", line 202, in sanitize_page
    scale = int(np.median(np.array(heights)))
ValueError: cannot convert float NaN to integer
```

The Region in question belongs to a Newspaper Digitalization.

It is possible to workaround at line 202 in repair.py (please see above) with with a check like

```
            _median = np.median(np.array(heights))
            if not np.isnan(_median):
                scale = int(_median)
            else:
                scale = 1
```
 
which finally yields at the same place

```
10:48:47.496 INFO processor.RepairSegmentation - Sanitizing region "region0071"
/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/hartwig/Projekte/ulb-dd-ocr-eval-ocrd/venv/lib/python3.6/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
10:48:47.699 WARNING processor.RepairSegmentation - Zero contour area in region "region0071"

```

but this way the processing move further.

**Comment by bertsky** [comment]
Are you sure this still happens after 70209929c18dede0c2971afcc7d1d928c8f7bbcb?

**Comment by M3ssman** [comment]
@bertsky 
Sorry, I can't see the commit. I've added `ocrd_all` as submodul, but when I run `git pull --recurse-submodules` , it is not update with your commit ... ?

Do I need to clone this repository for extra? Am I missing something?

**Comment by bertsky** [comment]
@M3ssman sorry, I should have mentioned there is no update for ocrd_all yet. You can update yourself though:
```sh
cd ocrd_all/ocrd_segment
git pull origin master
```

**Comment by bertsky** [comment]
Can we close?

**Comment by kba** [comment]
Yeah, this has been part of ocrd_all since https://github.com/OCR-D/ocrd_all/pull/61.
